((topmost-intro <0,0>) (cpp-macro))
((topmost-intro <1,0>) (cpp-macro))
((topmost-intro <2,0>))
((class-open <1,0>))
((inclass <1,0>) (topmost-intro <1,0>))
((inclass <2,0>) (topmost-intro <1,0>))
((inclass <3,0>) (access-label <3,0>))
((inclass <4,0>) (topmost-intro <2,0>))
((class-close <6,0>))
((topmost-intro <1,0>) (comment-intro))
((topmost-intro <2,0>) (comment-intro))
((topmost-intro <3,0>) (comment-intro))
((topmost-intro <4,0>) (comment-intro))
